"""add index to refresh token admin_id

Revision ID: 509406d5b023
Revises: a8aa1b2d9909
Create Date: 2026-09-16 20:11:20.356140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509406d5b023'
down_revision: Union[str, None] = 'a8aa1b2d9909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_token_admin_id'), 'refresh_token', ['admin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_admin_id'), table_name='refresh_token')
    # ### end Alembic commands ###
