"""add index and ondelete to request.user_id, add timestamps to user

Revision ID: 62ff249b2c0a
Revises: 509406d5b023
Create Date: 2026-09-16 22:41:21.646965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ff249b2c0a'
down_revision: Union[str, None] = '509406d5b023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_request_user_id'), 'request', ['user_id'], unique=False)
    op.drop_constraint(op.f('request_user_id_fkey'), 'request', type_='foreignkey')
    op.create_foreign_key('request_user_id_fkey', 'request', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('request_user_id_fkey', 'request', type_='foreignkey')
    op.create_foreign_key(op.f('request_user_id_fkey'), 'request', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_request_user_id'), table_name='request')
    # ### end Alembic commands ###
