"""add admin authentication fields

Revision ID: 6d91cd354239
Revises: dede26ad8e18
Create Date: 2026-09-14 18:50:58.412457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d91cd354239'
down_revision: Union[str, None] = 'dede26ad8e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('login', sa.String(length=50), nullable=False))
    op.add_column('admin', sa.Column('password_hash', sa.String(), nullable=False))
    op.alter_column('admin', 'tg_admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'admin', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin', type_='unique')
    op.alter_column('admin', 'tg_admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('admin', 'password_hash')
    op.drop_column('admin', 'login')
    # ### end Alembic commands ###
