"""add archived_request table

Revision ID: cc45698523fe
Revises: c6a8d9871257
Create Date: 2026-09-20 14:29:02.710617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc45698523fe'
down_revision: Union[str, None] = 'c6a8d9871257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_request_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='statusenum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_request_original_request_id'), 'archived_request', ['original_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archived_request_original_request_id'), table_name='archived_request')
    op.drop_table('archived_request')
    # ### end Alembic commands ###
